* Klarkson
** Sovitetaan testejä koodikantaan
[2023-04-23 Sun]

Meillä on pari testiluokkaa koodattuna, mutta ne ovat olleet kokeiluja
ilman assertioita. Siitä on ainakin vallan helppo aloittaa.

Triviaalit, funktionaaliset MiscUtilsit oli nyt ainakin triviaali
testata, mutta heti Queryparsinnan jutuissa päästään hieromaan enemmän
nystyröitä.

Helpomman testattavuuden nimissä jakakaamme ja refaktoroikaamme koodia
kanssa. Ja tietenkin TDD-tyyliin.

** TODO parseQuery tekee monta asiaa [/]
*** TODO parseQuery sekä parsii että luo regexiä
** TODO JavaMPD:n päivitys uusimpaan

Koska mentiin viimein uusimpaan JVM:ään niin uusimmat JavaMPD-versiot
ovat myös käytettävissäni.

** TODO Moduleiden organisointia paketteihin

Näyttää sitten paljon paremmalta.

** DONE Helppo mockattava: Songtest
CLOSED: [2023-04-26 Wed 15:39]
:LOGBOOK:
- State "DONE"       from "TODO"       [2023-04-26 Wed 15:39]
:END:

Mockaa MPD-kutsu pois. Nyt testin ajamiseen menee 300 ms, jos se luku
saadaan pienemmäksi niin bueno.

Laitetaan =MockK= testiin.

Mockattu versio saattaa tiedä vaikka toimia? Mutta se kestää nyt
nelinkertaisesti. Tietysti riippuvuus ulkoisista prosesseista MPD:stä
on ilman muuta poistettava, joten tämä on parempi kuin alkutilanne.

MockK toimii kivasti.
